version: "3.9"
services:
  backend:
    image: sudoku-backend
    container_name: sudoku-backend
    build:
      context: ./sudoku-backend
    ports:
      - "8080:8080"
#    networks:
#      - sudoku-net
  frontend:
    image: ng-sudoku
    container_name: ng-sudoku
    build:
      context: ./ng-sudoku
    ports:
      - "4200:4200"
#    networks:
#      - sudoku-net
    depends_on:
      - backend
#In case we need to create network, we can use below code
#networks:
#  sudoku-net: